add lstm model
GroupLe/grouple-face-tagger pull request #1
Opened 2021-07-07 12:10 UTC by maypink

2021-07-07 12:42 UTC, ARQtty requested changes

2021-07-07 12:42 UTC, ARQtty commented on models/NER/models/lstm/functions.py
> +def create_ris_dict():
docstring бы и типы возвращаемых аргументов

2021-07-07 12:42 UTC, ARQtty commented on models/NER/models/lstm/functions.py
> +def create_ris_dict():
для всех  функций, непонятных за 3 секунды

2021-07-07 12:42 UTC, ARQtty commented on models/NER/models/lstm/functions.py
> +    nums = [i + 1 for i in range(0, 33)]
мб `list(range(1, 33))` ?

2021-07-07 12:42 UTC, ARQtty commented on models/NER/models/lstm/functions.py
> +def encode(word, max_len):
мб сделать это с помощью embedding(word) и torch padding'a?

2021-07-07 12:42 UTC, ARQtty commented on models/NER/models/lstm/functions.py
> +    def to_probs(preds): sigmoid(preds)[:, 0].cpu().detach().numpy()
это страшнее, чем добавить линтовую ошибку про лямбды в игнор линтера

2021-07-07 12:42 UTC, ARQtty commented on models/NER/models/lstm/functions.py
> +    preds = [item for subl in preds for item in subl]
возможно `itertools.chain` или `from_chain` - это то что тебе нужно здесь

2021-07-07 12:42 UTC, ARQtty commented on models/NER/models/lstm/functions.py
> +    ix = np.argmax(fscore)
Если входные данные - тензоры (стоит указать типы аргументов функции), то мб полностью торч методами посчитать f-score?  Каст к np, из-за которого потом нужно импортировать np для вызова argmax выглядит накручиванием сложностей

2021-07-07 12:42 UTC, ARQtty commented on models/NER/models/lstm/model.py
> +class LSTM_fixed_len(nn.Module):
имена классов - camelCase. Странно, что линтер не заметил

2021-07-07 12:42 UTC, ARQtty commented on models/NER/models/lstm/model.py
> +
Ворд -> формат -> абзац -> межстрочный интервал -> 1.0?

2021-07-07 12:42 UTC, ARQtty commented on models/NER/models/lstm/model.py
> +        while len(cur_word) < max_len:
А если больше?

2021-07-07 12:42 UTC, ARQtty commented on models/NER/models/lstm/model.py
> +        encoded = torch.reshape(encoded, (1, 14))
Again а если слово длиннее?

2021-07-07 12:42 UTC, ARQtty commented on models/NER/models/lstm/model.py
> +    def save(self, path):
Раз save - метод класса, то стоит сделать и load методом

2021-07-07 12:42 UTC, ARQtty commented on models/NER/models/lstm/token_dataset.py
> +    def __getitem__(self, idx):
В целом делать one-hot encoding можно и здесь. Вся логика будет инкапсулирована в датасет. Так будет правильнее

2021-07-07 12:42 UTC, ARQtty commented on models/NER/models/lstm/token_dataset.py
> +class TokensDataset(Dataset):
тут бы ещё collate_fn определить

2021-07-07 20:55 UTC, maypink commented on models/NER/models/lstm/model.py
> +
![image](https://user-images.githubusercontent.com/57305249/124827417-b033f300-df7e-11eb-8ac4-6d6d6687b8e0.png)
поменяла на две, линтер кидает ошибку

2021-07-07 20:56 UTC, maypink commented on models/NER/models/lstm/functions.py
> +    nums = [i + 1 for i in range(0, 33)]
![image](https://user-images.githubusercontent.com/57305249/124827681-f4bf8e80-df7e-11eb-83b7-45fe0ceeb8b6.png)

2021-07-07 20:57 UTC, maypink commented on models/NER/models/lstm/functions.py
> +    def to_probs(preds): sigmoid(preds)[:, 0].cpu().detach().numpy()
твой же код взятый с auc из train_rubert

2021-07-07 21:07 UTC, ARQtty commented on models/NER/models/lstm/functions.py
> +    nums = [i + 1 for i in range(0, 33)]
не, коммент к 9ой строке

2021-07-07 21:09 UTC, ARQtty commented on models/NER/models/lstm/model.py
> +
Не, речь о том, что здесь вроде как между строками сильной логической разницы нет, поэтому нет смысла после каждой пустую ставить

2021-07-07 21:22 UTC, maypink commented on models/NER/models/lstm/model.py
> +class LSTM_fixed_len(nn.Module):
+

2021-07-07 21:22 UTC, maypink commented on models/NER/models/lstm/model.py
> +        while len(cur_word) < max_len:
+

2021-07-07 21:22 UTC, maypink commented on models/NER/models/lstm/model.py
> +        encoded = torch.reshape(encoded, (1, 14))
+

2021-07-07 21:28 UTC, maypink commented on models/NER/models/lstm/model.py
> +    def save(self, path):
+

2021-07-07 22:02 UTC, maypink commented on models/NER/models/lstm/functions.py
> +    preds = [item for subl in preds for item in subl]
это опять кусок твоего кода...))))

2021-07-08 11:53 UTC, ARQtty approved these changes

2021-07-08 11:53 UTC, merged