add web_component for reviews and chapters
GroupLe/grouple-face-tagger pull request #10
Opened 2021-08-02 15:35 UTC by maypink

2021-08-02 16:21 UTC, ARQtty requested changes

2021-08-02 16:21 UTC, ARQtty commented on backend/parse_manga/parse_faces.py
> +sys.path.insert(0, 'C:/may/ML/GroupLe/grouple/backend/parse_manga/parqser')
??????

2021-08-02 16:25 UTC, maypink commented on backend/parse_manga/parse_faces.py
> +sys.path.insert(0, 'C:/may/ML/GroupLe/grouple/backend/parse_manga/parqser')
по-другому у меня не работает....

2021-08-05 23:49 UTC, ARQtty commented on backend/parse_manga/parse_main_page.py
> +sys.path.insert(0, 'C:/may/ML/GroupLe/grouple/backend/parse_manga/parqser')
ну это не дело конечно

2021-08-05 23:50 UTC, ARQtty commented on backend/parse_manga/web_components/main_page/comments.py
> +class Comments(BaseComponent):
лучше соблюдать правило "один класс - один файл"

2021-08-05 23:51 UTC, ARQtty commented on backend/parse_manga/web_components/main_page/header.py
> +class MangaType(BaseComponent):
лучше соблюдать правило "один класс - один файл"

2021-08-05 23:51 UTC, ARQtty reviewed
супер

2021-08-06 11:02 UTC, maypink commented on backend/parse_manga/parse_main_page.py
> +sys.path.insert(0, 'C:/may/ML/GroupLe/grouple/backend/parse_manga/parqser')
ну дело-не дело, а по-другому никак

2021-08-06 13:46 UTC, ARQtty commented on backend/reproduce/00_get-manga-links.py
> +def get_links(df: pd.DataFrame) -> (List[str], List[str]):
Tuple[List[str], List[str]]

2021-08-06 13:48 UTC, ARQtty commented on backend/reproduce/00_get-manga-links.py
> +                        if re.search('^(\'https:\/\/static.readmanga).*', item) != None:
очень большая вложенность

2021-08-06 13:48 UTC, ARQtty reviewed
гуд

2021-08-09 21:19 UTC, ARQtty commented on backend/parse_manga/parse_main_page.py
> +sys.path.insert(0, 'C:/may/ML/GroupLe/grouple/backend/parse_manga/parqser')
это же ж в проде придётся подменять(

2021-08-09 21:19 UTC, ARQtty commented on backend/parse_manga/parse_manga.py
> +sys.path.insert(0, 'C:/may/ML/GroupLe/grouple/backend/parse_manga/parqser')
(

2021-08-09 21:20 UTC, ARQtty commented on backend/parse_manga/parse_manga.py
> +    def __init__(self, url):
типы

2021-08-09 21:21 UTC, ARQtty commented on backend/parse_manga/parse_manga.py
> +    def __init__(self, url):
лучше сделать это как
```
@classmethod
def from_url(url: str):
  pass
```
потому что иначе логика этого класса - не хранение данных о манге, а её скачивание. Тогда и называться он должен иначе

2021-08-09 21:21 UTC, ARQtty commented on backend/parse_manga/parse_manga.py
> +    def __init__(self, url):
бтв файл должен называться так же как класс (но с переводом в snake_case)

2021-08-09 21:22 UTC, ARQtty commented on backend/parse_manga/web_components/volumes/comments_page.py
> +    def parse(self, source: str) -> List[str]:
большая вложенность

2021-08-09 21:23 UTC, ARQtty commented on backend/parse_manga/web_components/volumes/comments_page.py
> +            if len(list(div.classes)) > 1:
вместо этого написать 
```
if len(list(div.classes)) <= 1:
  continue
```
уменьшит вложенность на 1 уровень

2021-08-09 21:24 UTC, ARQtty commented on backend/parse_manga/web_components/volumes/comments_page.py
> +                if class_name.startswith('cm_'):
вместо этого написать
```
if not class_name.startswith('cm_'):
  continue
```
уменьшит вложенность на 1 уровень

2021-08-09 21:25 UTC, ARQtty commented on backend/parse_manga/web_components/volumes/comments_page.py
> +                    for comm in comms_div:
тут можно использовать list comprehension вместо цикла

2021-08-09 21:25 UTC, ARQtty commented on backend/parse_manga/web_components/volumes/pics.py
> +        def get_links_substr(page_str: str) -> str:
вынести в отдельный приватный статичный метод

2021-08-09 21:26 UTC, ARQtty commented on backend/parse_manga/web_components/volumes/pics.py
> +        def make_links(links_substr: str) -> List[str]:
вынести в отдельный приватный статичный метод

2021-08-09 21:26 UTC, ARQtty reviewed
впервые за пулреквест написал полезных комментов

2021-08-09 22:33 UTC, maypink commented on backend/parse_manga/web_components/volumes/pics.py
> +        def get_links_substr(page_str: str) -> str:
с днем твоего кода

2021-08-09 22:34 UTC, maypink commented on backend/parse_manga/web_components/volumes/pics.py
> +        def make_links(links_substr: str) -> List[str]:
с днем твоего кода х2

2021-08-09 22:44 UTC, ARQtty commented on backend/parse_manga/manga.py
> +    def to_json(self) -> Dict[str, str]:
интерфейс бы

2021-08-09 22:45 UTC, ARQtty commented on backend/parse_manga/manga.py
> +    def parse_volumes(volumes: List[str]) -> List[Dict[str, Volume]]:
что за volumes? какие-то строки. Не сразу понятно, что это список ссылок

2021-08-09 22:51 UTC, ARQtty commented on backend/parse_manga/manga.py
> +    @classmethod
нееет, классметод нужен, чтобы возвращать объект текущего класса

2021-08-09 22:51 UTC, ARQtty commented on backend/parse_manga/manga.py
> +    def from_url(cls, url: str) -> json:
нет типа json. В этом коде json - это модуль. Если линтер твоей ide пропустил этого, посмотри живой ли он

2021-08-09 22:58 UTC, maypink commented on backend/parse_manga/manga.py
> +    def to_json(self) -> Dict[str, str]:
быбыбы

2021-08-09 23:00 UTC, ARQtty commented on backend/parse_manga/web_components/volumes/comments_page.py
> +            comments[int(num[0])] = comms
num определен сильно выше, но там нигде не используется. Может перенести его ближе к месту использования?

2021-08-09 23:01 UTC, ARQtty commented on backend/parse_manga/web_components/volumes/comments_page.py
> +            comments[int(num[0])] = comms
и вынести логику преобразования к типу и взятия по индексу в то же место, где num создается

2021-08-10 10:41 UTC, ARQtty commented on backend/parse_manga/manga.py
> +class BasePart:
поменять на более выразительное

2021-08-10 11:03 UTC, ARQtty commented on backend/parse_manga/manga.py
> +class Page(BasePart):
1 класс - 1 файл

2021-08-11 10:56 UTC, ARQtty commented on backend/parse_manga/manga.py
> +        self.ner_names = None
можно ещё картинки добавить

2021-08-11 10:57 UTC, ARQtty commented on backend/parse_manga/manga.py
> +        self.ner_names = None
и отдельный setter на них и на имена

2021-08-11 11:01 UTC, ARQtty requested changes
Всё гуд!
Добавь setter на ner names и pictures, и можно мержить

2021-08-11 11:55 UTC, ARQtty approved these changes
Finally

2021-08-11 11:58 UTC, merged