add parsing faces script
GroupLe/grouple-face-tagger pull request #9
Opened 2021-07-26 18:10 UTC by maypink

2021-07-26 23:17 UTC, ARQtty commented on models/face_recognition/reproduce/02-parse_faces.py
> +    path = Path('../../../data/face_detection/raw/characters/you_anime_characters_refs.csv/')
`.csv/`- это работает?

2021-07-26 23:18 UTC, ARQtty commented on models/face_recognition/reproduce/02-parse_faces.py
> +    with Pool(processes) as pool:
тебя забанят за ddos после десяти картинок

2021-07-26 23:19 UTC, ARQtty reviewed
Если бы всё было так просто

2021-07-27 07:27 UTC, maypink commented on models/face_recognition/reproduce/02-parse_faces.py
> +    with Pool(processes) as pool:
я скачала все и меня не забанили:(

2021-07-27 07:28 UTC, maypink commented on models/face_recognition/reproduce/02-parse_faces.py
> +    with Pool(processes) as pool:
и кстати, я пыталась заюзать твой парсер, но 
![image](https://user-images.githubusercontent.com/57305249/127113749-3c0b6fea-e7d6-40e9-9067-9bebeed98566.png)

2021-07-27 07:29 UTC, maypink commented on models/face_recognition/reproduce/02-parse_faces.py
> +    path = Path('../../../data/face_detection/raw/characters/you_anime_characters_refs.csv/')
да, но могу убрать этот бедный слеш

2021-07-28 20:06 UTC, ARQtty requested changes

2021-07-28 20:06 UTC, ARQtty commented on models/fandom_groupper/candidates_search.ipynb
> +    "    def __init__(self, name, pic, link):\n",
типы

2021-07-28 20:06 UTC, ARQtty commented on models/fandom_groupper/candidates_search.ipynb
> +    "    def __init__(self, df):\n",
типы

2021-07-28 20:06 UTC, ARQtty commented on models/fandom_groupper/candidates_search.ipynb
> +    "    def lemmatize(self, word):\n",
типы (возвращаемые в том числе)

2021-07-28 20:06 UTC, ARQtty commented on models/fandom_groupper/candidates_search.ipynb
> +    "    def get_info_name(self, name: str) -> List[Character]:\n",
восхитительные типы, спасибо

2021-07-28 20:06 UTC, ARQtty commented on models/fandom_groupper/candidates_search.ipynb
> +    "    def get_info_name(self, name: str) -> List[Character]:\n",
но нейминг метода так себе. Может что-то вроде `get_characters_by_name`?

2021-07-28 20:06 UTC, ARQtty commented on models/fandom_groupper/candidates_search.ipynb
> +    "        for i, (page_link, name, link, img_addr) in df_chars.iterrows():\n",
если колонки изменятся в порядке или количестве - перестанет работать. Лучше использовать что-то вроде 
`df[colnames].to_records(index=False)`

2021-07-28 20:06 UTC, ARQtty commented on models/fandom_groupper/candidates_search.ipynb
> +    "        for i, (page_link, name, link, img_addr) in df_chars.iterrows():\n",
кст `i` тебе тут не нужно

2021-07-28 20:06 UTC, ARQtty commented on models/fandom_groupper/candidates_search.ipynb
> +    "    def get_info(self, names: List[str]):\n",
тип

2021-07-28 20:06 UTC, ARQtty commented on models/fandom_groupper/candidates_search.ipynb
> +    "    def get_info(self, names: List[str]):\n",
нейминг метода так себе. Мб что-то вроде того же, что у первого метода, но во множественном числе, раз уж семантика та же?

2021-07-28 20:06 UTC, ARQtty commented on models/fandom_groupper/candidates_search.ipynb
> +    "    def get_info(self, names: List[str]):\n",
мб тут вполне читабельно будет даже с list comprehension

2021-07-28 22:29 UTC, ARQtty commented on models/fandom_groupper/candidates_search.ipynb
>      "import pandas as pd\n",
тут путаница в именах и info в названиях лишнее, но ты это уже знаешь

2021-07-29 10:21 UTC, ARQtty requested changes

2021-07-29 10:21 UTC, ARQtty commented on models/fandom_groupper/candidates_search.ipynb
> +    "    def get_character_by_name(self, name: str) -> List[Character]: \n",
get_character, а возвращает больше одного. Сомнительно

2021-07-29 10:44 UTC, ARQtty approved these changes

2021-07-30 13:13 UTC, merged